# Generated by Django 2.2.11 on 2020-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('char', models.CharField(max_length=256)),
            ],
        ),
    ]
