# Generated by Django 2.2.11 on 2020-03-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='basemodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BaseModel'),
        ),
    ]
