# Generated by Django 2.2.11 on 2020-03-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_examplemodel_basemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='char',
            new_name='name',
        ),
    ]
