# Generated by Django 2.2.11 on 2020-03-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200317_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='basemodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BaseModel'),
        ),
    ]
