# Generated by Django 2.2.11 on 2020-03-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200317_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='basemodel',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='identifier',
        ),
    ]
