# Generated by Django 2.2.11 on 2020-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200317_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
