# Generated by Django 2.2.11 on 2020-03-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_examplemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BaseModel'),
        ),
    ]
